package com.lovemm.mapper;

import com.lovemm.model.SResource;
import com.lovemm.model.SResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	long countByExample(SResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int deleteByExample(SResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String resId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int insert(SResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int insertSelective(SResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	List<SResource> selectByExample(SResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	SResource selectByPrimaryKey(String resId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SResource record, @Param("example") SResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SResource record, @Param("example") SResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_resource
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SResource record);
}