package com.lovemm.mapper;

import com.lovemm.model.SRole;
import com.lovemm.model.SRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	long countByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int deleteByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int insert(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int insertSelective(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	List<SRole> selectByExample(SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	SRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SRole record);

	/**
	 * @author pangpj 2017年03月28日16:59:28
	 * 根据角色id  获取权限数据
	 */
	List<SRole> getRolesByUserId(String userId);
}