package com.lovemm.mapper;

import com.lovemm.model.SResource;
import com.lovemm.model.SRoleResourcesExample;
import com.lovemm.model.SRoleResourcesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleResourcesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	long countByExample(SRoleResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int deleteByExample(SRoleResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(SRoleResourcesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int insert(SRoleResourcesKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int insertSelective(SRoleResourcesKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	List<SRoleResourcesKey> selectByExample(SRoleResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SRoleResourcesKey record,
			@Param("example") SRoleResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_role_resource
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SRoleResourcesKey record, @Param("example") SRoleResourcesExample example);

	/**
	 * @author pangpj 2017年03月28日17:15:34
	 * 根据角色id  获取角色资源
	 * @param userId 角色id
	 * @return
	 */
    List<SResource> getResourcesByUserId(String userId);
}