package com.lovemm.mapper;

import com.lovemm.model.SUserRoleExample;
import com.lovemm.model.SUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	long countByExample(SUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int deleteByExample(SUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(SUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int insert(SUserRoleKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int insertSelective(SUserRoleKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	List<SUserRoleKey> selectByExample(SUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SUserRoleKey record, @Param("example") SUserRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user_role
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SUserRoleKey record, @Param("example") SUserRoleExample example);
}