package com.lovemm.mapper;

import com.lovemm.model.SUser;
import com.lovemm.model.SUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	long countByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int deleteByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int insert(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int insertSelective(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	List<SUser> selectByExample(SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	SUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SUser record, @Param("example") SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SUser record, @Param("example") SUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table s_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SUser record);
}