package com.lovemm.model;

public class SResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_ID
	 * @mbg.generated
	 */
	private String resId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_NAME
	 * @mbg.generated
	 */
	private String resName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.P_RES_ID
	 * @mbg.generated
	 */
	private String pResId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_TYPE
	 * @mbg.generated
	 */
	private Integer resType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.STATUS
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_INDEX
	 * @mbg.generated
	 */
	private Integer resIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_URL
	 * @mbg.generated
	 */
	private String resUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.PERMISSION
	 * @mbg.generated
	 */
	private String permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_resource.RES_ICON
	 * @mbg.generated
	 */
	private String resIcon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_ID
	 * @return  the value of s_resource.RES_ID
	 * @mbg.generated
	 */
	public String getResId() {
		return resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_ID
	 * @param resId  the value for s_resource.RES_ID
	 * @mbg.generated
	 */
	public void setResId(String resId) {
		this.resId = resId == null ? null : resId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_NAME
	 * @return  the value of s_resource.RES_NAME
	 * @mbg.generated
	 */
	public String getResName() {
		return resName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_NAME
	 * @param resName  the value for s_resource.RES_NAME
	 * @mbg.generated
	 */
	public void setResName(String resName) {
		this.resName = resName == null ? null : resName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.P_RES_ID
	 * @return  the value of s_resource.P_RES_ID
	 * @mbg.generated
	 */
	public String getpResId() {
		return pResId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.P_RES_ID
	 * @param pResId  the value for s_resource.P_RES_ID
	 * @mbg.generated
	 */
	public void setpResId(String pResId) {
		this.pResId = pResId == null ? null : pResId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_TYPE
	 * @return  the value of s_resource.RES_TYPE
	 * @mbg.generated
	 */
	public Integer getResType() {
		return resType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_TYPE
	 * @param resType  the value for s_resource.RES_TYPE
	 * @mbg.generated
	 */
	public void setResType(Integer resType) {
		this.resType = resType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.STATUS
	 * @return  the value of s_resource.STATUS
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.STATUS
	 * @param status  the value for s_resource.STATUS
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_INDEX
	 * @return  the value of s_resource.RES_INDEX
	 * @mbg.generated
	 */
	public Integer getResIndex() {
		return resIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_INDEX
	 * @param resIndex  the value for s_resource.RES_INDEX
	 * @mbg.generated
	 */
	public void setResIndex(Integer resIndex) {
		this.resIndex = resIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_URL
	 * @return  the value of s_resource.RES_URL
	 * @mbg.generated
	 */
	public String getResUrl() {
		return resUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_URL
	 * @param resUrl  the value for s_resource.RES_URL
	 * @mbg.generated
	 */
	public void setResUrl(String resUrl) {
		this.resUrl = resUrl == null ? null : resUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.PERMISSION
	 * @return  the value of s_resource.PERMISSION
	 * @mbg.generated
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.PERMISSION
	 * @param permission  the value for s_resource.PERMISSION
	 * @mbg.generated
	 */
	public void setPermission(String permission) {
		this.permission = permission == null ? null : permission.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_resource.RES_ICON
	 * @return  the value of s_resource.RES_ICON
	 * @mbg.generated
	 */
	public String getResIcon() {
		return resIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_resource.RES_ICON
	 * @param resIcon  the value for s_resource.RES_ICON
	 * @mbg.generated
	 */
	public void setResIcon(String resIcon) {
		this.resIcon = resIcon == null ? null : resIcon.trim();
	}
}