package com.lovemm.model;

public class SRoleResourcesKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_role_resource.ROLE_ID
	 * @mbg.generated
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_role_resource.RES_ID
	 * @mbg.generated
	 */
	private String resId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_role_resource.ROLE_ID
	 * @return  the value of s_role_resource.ROLE_ID
	 * @mbg.generated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_role_resource.ROLE_ID
	 * @param roleId  the value for s_role_resource.ROLE_ID
	 * @mbg.generated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_role_resource.RES_ID
	 * @return  the value of s_role_resource.RES_ID
	 * @mbg.generated
	 */
	public String getResId() {
		return resId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_role_resource.RES_ID
	 * @param resId  the value for s_role_resource.RES_ID
	 * @mbg.generated
	 */
	public void setResId(String resId) {
		this.resId = resId == null ? null : resId.trim();
	}
}