package com.lovemm.model;

import java.util.Date;

public class SUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.USER_ID
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.USER_TEL
	 * @mbg.generated
	 */
	private String userTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.USER_MAIL
	 * @mbg.generated
	 */
	private String userMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.USER_ACCOUNT
	 * @mbg.generated
	 */
	private String userAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.USER_PWD
	 * @mbg.generated
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.STATUS
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.CREATE_TIME
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.REGISTER_IP
	 * @mbg.generated
	 */
	private String registerIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.LOGIN_TIMES
	 * @mbg.generated
	 */
	private Integer loginTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.LAST_LOGIN_IP
	 * @mbg.generated
	 */
	private String lastLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.LAST_LOGIN_TIME
	 * @mbg.generated
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.IS_LOCKED
	 * @mbg.generated
	 */
	private Integer isLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.PWD_WRONG_TIMES
	 * @mbg.generated
	 */
	private Integer pwdWrongTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user.NICK_NAME
	 * @mbg.generated
	 */
	private String nickName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.USER_ID
	 * @return  the value of s_user.USER_ID
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.USER_ID
	 * @param userId  the value for s_user.USER_ID
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.USER_TEL
	 * @return  the value of s_user.USER_TEL
	 * @mbg.generated
	 */
	public String getUserTel() {
		return userTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.USER_TEL
	 * @param userTel  the value for s_user.USER_TEL
	 * @mbg.generated
	 */
	public void setUserTel(String userTel) {
		this.userTel = userTel == null ? null : userTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.USER_MAIL
	 * @return  the value of s_user.USER_MAIL
	 * @mbg.generated
	 */
	public String getUserMail() {
		return userMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.USER_MAIL
	 * @param userMail  the value for s_user.USER_MAIL
	 * @mbg.generated
	 */
	public void setUserMail(String userMail) {
		this.userMail = userMail == null ? null : userMail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.USER_ACCOUNT
	 * @return  the value of s_user.USER_ACCOUNT
	 * @mbg.generated
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.USER_ACCOUNT
	 * @param userAccount  the value for s_user.USER_ACCOUNT
	 * @mbg.generated
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount == null ? null : userAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.USER_PWD
	 * @return  the value of s_user.USER_PWD
	 * @mbg.generated
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.USER_PWD
	 * @param userPwd  the value for s_user.USER_PWD
	 * @mbg.generated
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd == null ? null : userPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.STATUS
	 * @return  the value of s_user.STATUS
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.STATUS
	 * @param status  the value for s_user.STATUS
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.CREATE_TIME
	 * @return  the value of s_user.CREATE_TIME
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.CREATE_TIME
	 * @param createTime  the value for s_user.CREATE_TIME
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.REGISTER_IP
	 * @return  the value of s_user.REGISTER_IP
	 * @mbg.generated
	 */
	public String getRegisterIp() {
		return registerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.REGISTER_IP
	 * @param registerIp  the value for s_user.REGISTER_IP
	 * @mbg.generated
	 */
	public void setRegisterIp(String registerIp) {
		this.registerIp = registerIp == null ? null : registerIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.LOGIN_TIMES
	 * @return  the value of s_user.LOGIN_TIMES
	 * @mbg.generated
	 */
	public Integer getLoginTimes() {
		return loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.LOGIN_TIMES
	 * @param loginTimes  the value for s_user.LOGIN_TIMES
	 * @mbg.generated
	 */
	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.LAST_LOGIN_IP
	 * @return  the value of s_user.LAST_LOGIN_IP
	 * @mbg.generated
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.LAST_LOGIN_IP
	 * @param lastLoginIp  the value for s_user.LAST_LOGIN_IP
	 * @mbg.generated
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.LAST_LOGIN_TIME
	 * @return  the value of s_user.LAST_LOGIN_TIME
	 * @mbg.generated
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.LAST_LOGIN_TIME
	 * @param lastLoginTime  the value for s_user.LAST_LOGIN_TIME
	 * @mbg.generated
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.IS_LOCKED
	 * @return  the value of s_user.IS_LOCKED
	 * @mbg.generated
	 */
	public Integer getIsLocked() {
		return isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.IS_LOCKED
	 * @param isLocked  the value for s_user.IS_LOCKED
	 * @mbg.generated
	 */
	public void setIsLocked(Integer isLocked) {
		this.isLocked = isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.PWD_WRONG_TIMES
	 * @return  the value of s_user.PWD_WRONG_TIMES
	 * @mbg.generated
	 */
	public Integer getPwdWrongTimes() {
		return pwdWrongTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.PWD_WRONG_TIMES
	 * @param pwdWrongTimes  the value for s_user.PWD_WRONG_TIMES
	 * @mbg.generated
	 */
	public void setPwdWrongTimes(Integer pwdWrongTimes) {
		this.pwdWrongTimes = pwdWrongTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user.NICK_NAME
	 * @return  the value of s_user.NICK_NAME
	 * @mbg.generated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user.NICK_NAME
	 * @param nickName  the value for s_user.NICK_NAME
	 * @mbg.generated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}
}