package com.lovemm.model;

public class SUserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_role.USER_ID
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_user_role.ROLE_ID
	 * @mbg.generated
	 */
	private String roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_role.USER_ID
	 * @return  the value of s_user_role.USER_ID
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_role.USER_ID
	 * @param userId  the value for s_user_role.USER_ID
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_user_role.ROLE_ID
	 * @return  the value of s_user_role.ROLE_ID
	 * @mbg.generated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_user_role.ROLE_ID
	 * @param roleId  the value for s_user_role.ROLE_ID
	 * @mbg.generated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}
}